import { Baskervville, Work_Sans } from "next/font/google";
import "./globals.css";

const baskervville = Baskervville({
  variable: "--font-baskervville",
  subsets: ["latin"],
})

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${baskervville.variable} ${workSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
